### ISSUE TITLE
Error linking for arm64 with openssl.

### ISSUE THREAD

**Issue by lobovkin** [sinofool/build-libcurl-ios#1]
Hello. Error linking for arm64 in Xcode then builded with openssl (without openssl all is OK).
I've fixed this: replace "--with-ssl=${HOME}/Desktop/openssl-ios-dist" with "--with-darwinssl".

**Comment by sinofool** [comment]
@lobovkin Thanks for the advice, I will create a switch about openssl and darwinssl.

**Comment by sinofool** [comment]
http://curl.haxx.se/docs/adv_20150108A.html
To use darwin native ssl, I will also add a version check to make sure no vulnerable version build

**Comment by sinofool** [comment]
Checkout the latest script. It will build with darwin ssl by default.
I am still using openssl algorithm in my project, but I think most of other project not. So I added a switch to build with openssl.

Thanks @lobovkin for the suggestion.
