### ISSUE TITLE
脚本注释掉了对32位设备的支持？

### ISSUE THREAD

**Issue by CHN-STUDENT** [sinofool/build-libcurl-ios#10]
我需要修改一下脚本？

**Comment by sinofool** [comment]
是的，32位的模拟器用的i386去掉了。
日常的开发用的太少，需要用到的自己加上吧。

**Comment by CHN-STUDENT** [comment]
另外还有一个问题，我用脚步编译最新版7.54到最后打补丁和复制文件时就停止了，提示找不到补丁文件...

**Comment by sinofool** [comment]
我试了7.54.0，没有遇到问题。
你看一下之前的错误提示，是不是下载patch文件出错了。

**Comment by CHN-STUDENT** [comment]
可能是网络原因，我手工使用终端操作了，感谢您的帮助！
