### ISSUE TITLE
What's the advantage of libcurl over NSURLSession?

### ISSUE THREAD

**Issue by skyline75489** [sinofool/build-libcurl-ios#11]
Just out of curiosity ❓

**Comment by sinofool** [comment]
Different language, not advantage.
I have business logic code written in C++, which shared between iOS/Android/WinPhone.
This is the reason I need different network libraries on different platforms.

Similar approach can also be accomplished at more higher level, like Xamarin and Qt.

**Comment by skyline75489** [comment]
Got it. Thanks.
