### ISSUE TITLE
curlbuild.h : No such file or directory

### ISSUE THREAD

**Issue by rudyryk** [sinofool/build-libcurl-ios#12]
Thank you for the build script! Seems like it worked for me but I see the following error at the final patching stage:

```bash
patch: **** Can't find file /tmp/build_libcurl_7488/include/curl/curlbuild.h : No such file or directory

$ ls  /tmp/build_libcurl_7488/include/curl/
curl.h          easy.h          multi.h         system.h
curlver.h       mprintf.h       stdcheaders.h   typecheck-gcc.h
```

curl-7.55.1
macOS 10.12.6
Xcode 8.3.2
Build version 8E2002

**Comment by sinofool** [comment]
Which version of the curl?

**Comment by rudyryk** [comment]
@sinofool curl-7.55.1

This is one that currently available for download as default at https://curl.haxx.se/download.html

**Comment by sinofool** [comment]
Newer 7.55 already support 64bit preprocessors in system.h header file.
I am working on an fix for latest version.
