### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by vasyl-kreveha** [sinofool/build-libcurl-ios#4]
Hey,

Your script works like a charm!
The only question is how can I enable HTTP/2 support here?

Cheers,
Vasiliy

**Comment by sinofool** [comment]
It will need --enable-nghttp2 flag while configuration. ( https://curl.haxx.se/docs/http2.html )
nghttp2 is a C library and looks not difficult to compile for mobile platforms. ( https://github.com/nghttp2/nghttp2 )
I will look into this issue later next week after a short trip.

Thanks for bring this up.

**Comment by sinofool** [comment]
As there is no progress over a year. I am closing this issue.

My recent projects are not using C++ as shared components.
Swagger codegen is currently my favorite solution of cross platform app development.
